name: river_movies
description: Movies app to test Riverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # project packages
  movies:
    path: ./packages/movies

  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  flutter_dotenv: ^2.1.0
  flutter_riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^1.0.3

flutter:
  uses-material-design: true
